server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /webfile
    encoding:
      force: true
      charset: utf-8
      enabled: true




file-manager:
  thumbnail:
    width: 80 # 缩略图宽
  volumes:
    - Node:
      source: fileSystem # 暂时只支持本地文件系统
      alias: 临时目录 # 目录别名
      path: /tmp/app # 映射目录
      locale:
      constraint:
        locked: false # 文件夹是否锁定
        readable: true # 是否可读
        writable: false # 是否可写

spring:
  security:
    user:
      name: user
      password: password
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
